version: "3.9"

services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    restart: on-failure

  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    command: npm run start
    environment:
      - NODE_ENV=production

volumes:
  dbdata6: